apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mailhog
    namespace: shop-system
spec:
    replicas: 1
    selector: { matchLabels: { app: mailhog } }
    template:
        metadata: { labels: { app: mailhog } }
        spec:
            containers:
                - name: mailhog
                  image: mailhog/mailhog
                  ports:
                      - containerPort: 8025
                      - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
    name: mailhog
    namespace: shop-system
spec:
    type: NodePort
    selector:
        app: mailhog
    ports:
        - name: ui
          port: 8025
          targetPort: 8025
          nodePort: 30225
        - name: smtp
          port: 1025
          targetPort: 1025
