apiVersion: apps/v1
kind: Deployment
metadata: 
    name: redis
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: local
spec:
    replicas: 1
    selector: { matchLabels: { app.kubernetes.io/component: redis } }
    template:
        metadata: 
            labels: 
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: redis
                app.kubernetes.io/instance: local
        spec:
            containers:
                - name: redis
                  image: redis:7.4
                  ports: [{ containerPort: 6379 }]
                  volumeMounts:
                      - mountPath: /data
                        name: redis-storage
            volumes:
                - name: redis-storage
                  persistentVolumeClaim:
                      claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata: 
    name: redis
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: local
spec:
    type: NodePort
    selector: { app.kubernetes.io/component: redis }
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
          nodePort: 30379
