doctrine_migrations:
    migrations_paths:
        'AuthModuleDoctrineMigrations': '%kernel.project_dir%/src/Module/Auth/Infrastructure/Doctrine/Migrations'
        'CommerceModuleDoctrineMigrations': '%kernel.project_dir%/src/Module/Commerce/Infrastructure/Doctrine/Migrations'
    enable_profiler: false
