services:
    nginx:
        image: nginx:1.27.2-alpine
        ports:
            - "80:80"
        restart: on-failure
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    php:
        build:
            context: ./docker/php
        restart: on-failure
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:9.1
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        restart: on-failure
        ports:
            - "6379:6379"
        volumes:
            - ./var/redis:/data

volumes:
    mysql:
