services:
    shop-system-mysql:
        container_name: shop-system-mysql
        image: mysql:9.1
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    shop-system-elasticsearch:
        container_name: shop-system-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    shop-system-redis:
        container_name: shop-system-redis
        image: redis:7.4
        restart: on-failure
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/data:/data
            
    shop-system-rabbitmq:
        container_name: shop-system-rabbitmq
        image: rabbitmq:4.1-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./docker/rabbitmq/data:/var/lib/rabbitmq

    shop-system-mailhog:
        container_name: shop-system-mailhog
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"

    shop-system-backend:
        container_name: shop-system-backend
        build:
            context: ./docker/php
        restart: always
        volumes:
            - .:/var/www:cached
        depends_on:
            - shop-system-mysql
            - shop-system-elasticsearch
            - shop-system-redis
            - shop-system-rabbitmq
            - shop-system-mailhog

    shop-system-frontend:
        container_name: shop-system-frontend
        image: node:23-alpine
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./frontend:/var/www/html
        working_dir: /var/www/html
        restart: on-failure
        stdin_open: true
        tty: true

    shop-system-nginx:
        container_name: shop-system-nginx
        image: nginx:1.27.2-alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - shop-system-backend
            - shop-system-frontend

volumes:
    frontend_node_modules:
