services:
    shop-system-nginx:
        container_name: shop-system-nginx
        build:
            context: ./docker/nginx
        restart: on-failure
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - shop-system

    shop-system:
        container_name: shop-system
        build:
            context: ./docker/php
        restart: on-failure
        volumes:
            - ./:/var/www/html
        depends_on:
            - shop-system-database
            - shop-system-cache

    shop-system-database:
        container_name: shop-system-database
        image: mysql:9.1
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    shop-system-cache:
        container_name: shop-system-cache
        image: redis:7.4
        restart: on-failure
        ports:
            - "6379:6379"
        volumes:
            - ./var/redis:/data

volumes:
    mysql:
