name: "Common Minimal Setup"
description: "Setup PHP, download artifacts, restore permissions"
runs:
    using: "composite"
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: "8.4"

        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
              name: build-files

        - name: Restore executable permissions
          shell: bash
          run: chmod +x vendor/bin/*
