apiVersion: v1
kind: Service
metadata:
    name: mysql
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: mysql
        app.kubernetes.io/instance: local
spec:
    type: NodePort
    selector: { app.kubernetes.io/component: mysql }
    ports:
        - name: mysql
          port: 3306
          targetPort: 3306
          nodePort: 30306
