apiVersion: apps/v1
kind: Deployment
metadata:
    name: shop-backend
    namespace: shop-system
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shop-backend
    template:
        metadata:
            labels:
                app: shop-backend
        spec:
            containers:
                - name: backend
                  image: maciekiwaniuk/shop-system-backend:latest
                  envFrom:
                      - configMapRef:
                            name: shop-backend-config
                      - secretRef:
                            name: shop-backend-secrets
                  ports:
                      - containerPort: 9000
                  readinessProbe:
                      httpGet:
                          path: /_health
                          port: 9000
                      initialDelaySeconds: 10
                      periodSeconds: 5
                  livenessProbe:
                      httpGet:
                          path: /_health
                          port: 9000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  resources:
                      requests:
                          cpu: "200m"
                          memory: "256Mi"
                      limits:
                          cpu: "500m"
                          memory: "512Mi"
                  volumeMounts:
                      - name: app-code
                        mountPath: /var/www
            volumes:
                - name: app-code
                  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    name: shop-backend
    namespace: shop-system
spec:
    type: ClusterIP
    selector:
        app: shop-backend
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
