apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: elasticsearch-pvc
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: elasticsearch
        app.kubernetes.io/instance: local
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
