apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rabbitmq-pvc
    namespace: shop-system
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
