parameters:
    redis_url: '%env(REDIS_URL)%'
    redis_app_prefix: '%env(REDIS_APP_PREFIX)%'
    elasticsearch_host: '%env(ELASTICSEARCH_HOST)%'
    elasticsearch_port: '%env(int:ELASTICSEARCH_PORT)%'
    elasticsearch_scheme: '%env(ELASTICSEARCH_SCHEME)%'
    payments_service_url: '%env(PAYMENTS_SERVICE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Module/Auth/Domain/Entity'
            - '../src/Module/Commerce/Domain/Entity'
            - '../src/Kernel.php'

    App\Module\Commerce\Domain\Repository\OrderRepositoryInterface:
        class: 'App\Module\Commerce\Infrastructure\Doctrine\Repository\OrderRepository'
    App\Module\Commerce\Domain\Repository\ProductRepositoryInterface:
        class: 'App\Module\Commerce\Infrastructure\Doctrine\Repository\ProductRepository'
    App\Module\Auth\Domain\Repository\UserRepositoryInterface:
        class: 'App\Module\Auth\Infrastructure\Doctrine\Repository\UserRepository'

    App\Module\Auth\Application\EventSubscriber\AuthenticationSuccessSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    App\Module\Auth\Application\EventSubscriber\AuthenticationFailureSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\Common\Infrastructure\Cache\CacheCreator:
        arguments:
            $redisUrl: '%redis_url%'
            $redisAppPrefix: '%redis_app_prefix%'

    Elastic\Elasticsearch\Client:
        factory: [ 'App\Module\Commerce\Infrastructure\Elasticsearch\ElasticsearchClientFactory', 'createClient' ]
        arguments:
            - '%elasticsearch_host%'
            - '%elasticsearch_port%'
            - '%elasticsearch_scheme%'

    App\Module\Commerce\Infrastructure\Elasticsearch\ProductIndexManager:
        arguments:
            $elasticsearchClient: '@Elastic\Elasticsearch\Client'
            $environment: '%kernel.environment%'

    App\Module\Commerce\Infrastructure\Adapter\PaymentsInitializerAdapter:
        arguments:
            $httpClient: '@http_client'
            $logger: '@Psr\Log\LoggerInterface'
            $paymentsServiceUrl: '%payments_service_url%'

imports:
    - { resource: 'services/commands.yaml' }
    - { resource: 'services/queries.yaml' }
