apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: local
type: Opaque
stringData:
#    DATABASE_URL: "mysql://shop_user:shop_password@mysql:3306/shop_system_auth"
