apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: nginx
        app.kubernetes.io/instance: local
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: nginx
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: nginx
                app.kubernetes.io/instance: local
        spec:
            initContainers:
                - name: setup-code
                  image: maciekiwaniuk/shop-system-backend:latest
                  command: [ "cp", "-a",  "/var/www/.", "/app" ]
                  volumeMounts:
                      -   name: app-code
                          mountPath: /app
            volumes:
                - name: app-code
                  emptyDir: {}
                - name: nginx-config
                  configMap:
                      name: nginx-config
            containers:
                - name: nginx
                  image: nginx:1.27.2-alpine
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: default.conf
                      - name: app-code
                        mountPath: /var/www
