apiVersion: v1
kind: Service
metadata:
    name: elasticsearch
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: elasticsearch
        app.kubernetes.io/instance: local
spec:
    type: NodePort
    selector: { app.kubernetes.io/component: elasticsearch }
    ports:
        - name: http
          port: 9200
          targetPort: 9200
          nodePort: 30920
