apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: local
spec:
    type: NodePort
    selector: { app.kubernetes.io/component: redis }
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
          nodePort: 30379
