apiVersion: v1
kind: ConfigMap
metadata:
    name: shop-backend-config
    namespace: shop-system
data:
    APP_ENV: "dev"
    APP_SECRET: "d657ff74809d228235168b242d0269aa"
    COMPOSE_PROJECT_NAME: "shop_system"
    MYSQL_HOST: "mysql"
    AUTH_MYSQL_DATABASE: "shop_system_auth"
    AUTH_MYSQL_USER: "shop_user"
    AUTH_MYSQL_PASSWORD: "shop_password"
    AUTH_DATABASE_URL: "mysql://shop_user:shop_password@mysql:3306/shop_system_auth?serverVersion=9.1"
    AUTH_DATABASE_TEST_URL: "mysql://shop_user:shop_password@mysql:3306/shop_system_auth_test?serverVersion=9.1"
    COMMERCE_MYSQL_DATABASE: "shop_system_commerce"
    COMMERCE_MYSQL_USER: "shop_user"
    COMMERCE_MYSQL_PASSWORD: "shop_password"
    COMMERCE_DATABASE_URL: "mysql://shop_user:shop_password@mysql:3306/shop_system_commerce?serverVersion=9.1"
    COMMERCE_DATABASE_TEST_URL: "mysql://shop_user:shop_password@mysql:3306/shop_system_commerce_test?serverVersion=9.1"
    REDIS_URL: "redis://redis/0"
    MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
    JWT_PASSPHRASE: "bf89a24b955e355bca0d41c7d3850dc251441d80f08e024acd73b40500b9b0a7"
    JWT_TOKEN_TTL: "3600"
    MAILER_DSN: "smtp://mailhog:1025"
    CORS_ALLOW_ORIGIN: "^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"
    ELASTICSEARCH_HOST: "elasticsearch"
    ELASTICSEARCH_PORT: "9200"
    ELASTICSEARCH_SCHEME: "http"
