apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mailhog
    namespace: shop-system
spec:
    replicas: 1
    selector: { matchLabels: { app: mailhog } }
    template:
        metadata: { labels: { app: mailhog } }
        spec:
            containers:
                - name: mailhog
                  image: mailhog/mailhog
                  ports:
                      - containerPort: 8025
                      - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata: 
    name: mailhog
    namespace: shop-system
spec:
    ports:
        - name: ui
          port: 8025
        - name: smtp
          port: 1025
    selector: { app: mailhog }
