apiVersion: apps/v1
kind: Deployment
metadata:
    name: queue
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop
        app.kubernetes.io/component: queue
        app.kubernetes.io/part-of: shop-system
spec:
    replicas: 2
    selector:
        matchLabels:
            app.kubernetes.io/component: queue
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop
                app.kubernetes.io/component: queue
        spec:
            terminationGracePeriodSeconds: 90
            volumes:
                - name: app-code
                  emptyDir: {}
            initContainers:
                - name: setup-code
                  image: maciekiwaniuk/shop-system-backend:latest
                  command: ["cp", "-a", "/var/www/.", "/app"]
                  volumeMounts:
                      - name: app-code
                        mountPath: /app
            containers:
                - name: queue-worker
                  image: maciekiwaniuk/shop-system-backend:latest
                  command: ["php", "/var/www/bin/console", "messenger:consume", "async", "--memory-limit=128M", "--time-limit=3600", "-vv"]
                  envFrom:
                      - configMapRef: { name: shop-backend-config }
                      - secretRef:    { name: shop-backend-secrets }
                  volumeMounts:
                      - name: app-code
                        mountPath: /var/www
